spring.application.name=CiCdDemo

spring.data.redis.host=redis
spring.data.redis.port=6379
spring.data.redis.timeout=60000

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://74.225.174.33:5433/testing
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA/Hibernate Configuration
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# A strong, Base64-encoded secret key. Generate your own!
jwt.secret=YmFzZTY0LWVuY29kZWQtc3Ryb25nLXNlY3JldC1rZXktZm9yLWp3dC1hdXRoZW50aWNhdGlvbg==

# Token expiration time in milliseconds (e.g., 24 hours)
jwt.expiration=86400000
server.domain=tiny-lane.duckdns.org:8081
server.port = 8080
total.api.request.allowed=5
fb.config.path=${FB_CONFIG_PATH:/Users/abhay/google/firebase/tiny-lane-config.json}

spring.profiles.active=dev
logging.level.com.as.CiCdDemo=DEBUG

# hikari the shikari properties
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=540000
spring.datasource.hikari.keepalive-time=300000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.validation-timeout=5000

# rate limiting properties
rate.limit.shorten.window.size=86400
rate.limit.shorten.allowed.requests=50
rate.limit.redirection.window.size=60
rate.limit.redirection.window.allowed.requests=50

id.range.increment.window.size=100000