package com.as.UrlShortner.service;

import com.as.UrlShortner.dto.UrlShortnerRequest;
import com.as.UrlShortner.dto.UrlShortnerResponse;
import com.as.UrlShortner.exceptions.KeyNotFoundException;
import com.as.UrlShortner.model.UrlMappings;
import com.as.UrlShortner.repository.UrlMappingRepository;
import jakarta.persistence.EntityManager;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.data.redis.core.StringRedisTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.Instant;
import java.util.Optional;
import java.util.concurrent.TimeUnit;

@Service
@Slf4j
public class UrlShortenerService {

    public Base62 encoder;
    private UrlMappingRepository urlMappingRepository;
    private String baseUrl;
    EntityManager entityManager;
    private StringRedisTemplate redisTemplate;
    private final IdGeneratorService idGeneratorService;

    public UrlShortenerService(Base62 encoder,@Value("${server.domain}") String domain,UrlMappingRepository urlMappingRepository,EntityManager entityManager,StringRedisTemplate redisTemplate,IdGeneratorService idGeneratorService){

        this.encoder = encoder;
        this.urlMappingRepository = urlMappingRepository;
        baseUrl = String.format("https://%s/s/", domain);
        this.entityManager = entityManager;
        this.redisTemplate = redisTemplate;
        this.idGeneratorService = idGeneratorService;
    }

    @Transactional
    public UrlShortnerResponse process(UrlShortnerRequest request) {
        try {

            long nextId = idGeneratorService.getNextid();
            //log.info("id generated by service: " + idGeneratorService);
            String originalUrl = request.getUrl().trim();
            String key = encoder.encode(nextId);
            UrlMappings newUrl = new UrlMappings(originalUrl,Instant.now(),key,nextId);

            UrlMappings entityWithId = urlMappingRepository.save(newUrl);
            String shortUrl = (baseUrl + key);
            return UrlShortnerResponse.builder().shortUrl(shortUrl).build();
        } catch (Exception e) {

            log.info(e.getMessage());
            throw new RuntimeException(e);
        }
    }

    @Transactional
    public String getUrl(String key) throws KeyNotFoundException {
        if(key == null || key.isBlank()) throw new RuntimeException("URL not found ");
        try {
            String redisKey = "URL:" + key;
            String result = redisTemplate.opsForValue().get(redisKey);
            if("NOT_FOUND".equalsIgnoreCase(result)) return null;

            if (result == null) {
                // cache miss scenario
                log.info("cache miss scenario key: " + key);
                // fetch from DB and write back to cache synchronously
                return urlMappingRepository.findByShortKey(key)
                        .map(url -> {
                            redisTemplate.opsForValue().set(redisKey, url.getOriginalUrl(), 24, TimeUnit.HOURS);
                            return url.getOriginalUrl();
                        })
                        .orElseGet(() -> {
                            // updating cache with NOT_FOUND to protect the DB from DDos
                            redisTemplate.opsForValue().set(redisKey, "NOT_FOUND", 1, TimeUnit.HOURS);
                            return null;
                        });
            }
            log.info("cache hit key: " + key);
            return result;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }

    }


}
