name: Push Image and Deploy

on:
  push:
    branches: [ master,development ]

jobs:
  docker-deploy:
    name: Docker Build & Deploy
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: deadshot007/distroless-image-java
      CONTAINER_NAME: distroless-app

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Package application
        run: mvn package -DskipTests

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Use short SHA
        id: meta
        run: echo "short_sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build & Push Docker Image
        env:
          SHORT_SHA: ${{ steps.meta.outputs.short_sha }}
        run: |
          echo $SHORT_SHA
          docker build -t $IMAGE_NAME:$SHORT_SHA .
          docker push $IMAGE_NAME:$SHORT_SHA

      - name: Display build summary
        run: |
          echo "✅ image created successfully & pushed to dockerHub !!"
