name: Push Image and Deploy

on:
  push:
    branches: [ master,development ]

jobs:
  docker-deploy:
    name: Docker Build & Deploy
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: deadshot007/distroless-image-java
      CONTAINER_NAME: distroless-app

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Package application
        run: mvn package -DskipTests

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Use short SHA
        id: meta
        run: echo "short_sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Set up QEMU (for cross-arch builds)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push Multi-Arch Docker Image
        env:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          SHORT_SHA: ${{ steps.meta.outputs.short_sha }}
        run: |
          echo "🔧 Building and pushing image: $IMAGE_NAME:$SHORT_SHA"
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag $IMAGE_NAME:$SHORT_SHA \
            --push \
            .

      - name: Display build summary
        run: |
          echo "✅ image created successfully & pushed to dockerHub !!"
