name: Push Image and Deploy

on:
  push:
    branches: [ master,development ]

jobs:
  docker-deploy:
    name: Docker Build & Deploy
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: deadshot007/distroless-image-java
      CONTAINER_NAME: distroless-app-java
      SECRET_PATH_VM: /home/isagi/.secrets
      SECRET_PATH_CON: /app/.secrets
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Package application
        run: mvn package -DskipTests

      - name: Download OpenTelemetry Java Agent
        run: |
          curl -L -o opentelemetry-javaagent.jar https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/latest/download/opentelemetry-javaagent.jar

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Use short SHA
        id: meta
        run: echo "short_sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Set up QEMU (for cross-arch builds)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push Multi-Arch Docker Image
        env:
          SHORT_SHA: ${{ steps.meta.outputs.short_sha }}
        run: |
          echo "🔧 Building and pushing image: $IMAGE_NAME:$SHORT_SHA"
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag $IMAGE_NAME:$SHORT_SHA \
            --push \
            .

      - name: Display build summary
        run: |
          echo "✅ image created successfully & pushed to dockerHub !!"

      - name: Deploy on Remote Server via SSH
        env:
          SHORT_SHA: ${{ steps.meta.outputs.short_sha }}
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: IMAGE_NAME,CONTAINER_NAME,SHORT_SHA,SECRET_PATH_VM,SECRET_PATH_CON
          script: |
            echo "📦 Pulling Docker image"
            docker pull $IMAGE_NAME:$SHORT_SHA

            echo "🛑 Stopping old container (if running)"
            docker stop $CONTAINER_NAME || true

            echo "🧹 Removing old container (if exists)"
            docker rm $CONTAINER_NAME || true

            echo "🚀 Running new container"
            docker run -d --name $CONTAINER_NAME \
              --network isagi_default \
              --network observability \
              -p 8080:8080 \
              -v $SECRET_PATH_VM:$SECRET_PATH_CON:ro \
              -e FB_CONFIG_PATH=$SECRET_PATH_CON \
              -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
              -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              -e OTEL_SERVICE_NAME=url-shortener \
              -e OTEL_METRICS_EXPORTER=prometheus \
              -e OTEL_EXPORTER_PROMETHEUS_PORT=9464 \
              -e OTEL_TRACES_EXPORTER=otlp \
              -e OTEL_LOGS_EXPORTER=otlp \
              -e OTEL_EXPORTER_OTLP_LOGS_ENDPOINT=http://loki:3100/loki/api/v1/push \
              -e OTEL_EXPORTER_OTLP_LOGS_PROTOCOL=http/protobuf \
              $IMAGE_NAME:$SHORT_SHA

            echo "✅ Deployed successfully!"
